import Head from "next/head"
import Link from "next/link"
import React, { useContext } from "react"
import { TfiInstagram } from "react-icons/tfi"
import LocalizationContext from "../context/LocalizationContext"
import styles from "../styles/layout.module.scss"
import LocalizedLabel from "./LocalizedLabel"
import Navigation from "./Navigation"

interface PageProps extends React.HTMLProps<HTMLDivElement> {
    children?: React.ReactNode
    pageTitle?: [DE: string, EN: string]
    showNav?: boolean
}

const Page = ({ children, pageTitle, showNav, ...rest }: PageProps) => {
    const localizationContext = useContext(LocalizationContext)

    return (
        <>
            <Head>
                <title>Lennard Fickus | Fotograf</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.page}>
                {showNav ? <Navigation /> : undefined}

                <div className={styles.container}>
                    <main {...rest}>
                        {pageTitle === undefined ? undefined : (
                            <h1 className={styles.title}>
                                {localizationContext.currentLanguage === "DE"
                                    ? pageTitle[0]
                                    : pageTitle[1]}
                            </h1>
                        )}
                        {children}
                    </main>

                    <footer>
                        <div className={styles.container}>
                            <ul className={styles.links}>
                                <li>
                                    <Link href="/privacy">
                                        <LocalizedLabel
                                            de="Datenschutzerklärung"
                                            en="Privacy policy"
                                        />
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/inprint">
                                        <LocalizedLabel
                                            de="Impressum"
                                            en="inprint"
                                        />
                                    </Link>
                                </li>
                            </ul>
                            <hr />
                            <ul className={styles.socialMedia}>
                                <li>
                                    <Link href="https://www.instagram.com/lennardfi/">
                                        <TfiInstagram />
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </footer>
                </div>
            </div>
        </>
    )
}
export default Page
