import Head from "next/head"
import React, { useContext } from "react"
import LocalizationContext from "../../context/LocalizationContext/LocalizationContext"
import Footer from "../Footer/Footer"
import Navigation from "../Navigation/Navigation"
import styles from "./Page.module.scss"

interface PageProps extends React.HTMLProps<HTMLDivElement> {
    children?: React.ReactNode
    containerProps?: React.HTMLProps<HTMLDivElement>
    hideNav?: boolean
    hideFooter?: boolean
    /**
     * Disable default mechanism to limit content width to 680px.
     */
    fullWidth?: boolean
    pageTitle?: [DE: string, EN: string]
}

const Page = ({
    children,
    className,
    containerProps,
    hideNav,
    hideFooter,
    fullWidth,
    pageTitle,
    ...rest
}: PageProps) => {
    const localizationContext = useContext(LocalizationContext)
    const { className: containerClassName, ...containerRest } =
        containerProps ?? {}

    return (
        <>
            <Head>
                <title>Lennard Fickus | Fotograf</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.page}>
                {hideNav ? undefined : <Navigation />}

                <div
                    className={`${styles.container} ${
                        containerClassName ?? ""
                    }`}
                    {...containerRest}
                >
                    <main
                        className={`${fullWidth ? "" : styles.limitWidth} ${
                            className ?? ""
                        }`}
                        {...rest}
                    >
                        {pageTitle === undefined ? undefined : (
                            <h1 className={styles.title}>
                                {localizationContext.currentLanguage === "DE"
                                    ? pageTitle[0]
                                    : pageTitle[1]}
                            </h1>
                        )}
                        {children}
                    </main>

                    {hideFooter ? undefined : <Footer />}
                </div>
            </div>
        </>
    )
}
export default Page
